export const AddTodo="AddTodo"
export const EditTodo="EditTodo"
export const SaveTodo="SaveTodo"
export const DeletTodo="DeletTodo"
export const DoneTodo="DoneTodo"
export const FilterAll="FilterAll"
export const FilterDone="FilterDone"
export const FilterDoneNot="FilterDoneNot"